apiVersion: apps/v1
kind: Deployment
metadata:
  name: category-service-deployment
  labels:
    app: category-service-label
spec:
  selector:
    matchLabels:
      app: category-service-label
  replicas: 1
  template:
    metadata:
      name: category-service-pod
      labels:
        app: category-service-label
    spec:
      containers:
        - name: category-service-container
          image: sokol111/category-service:latest
          ports:
            - containerPort: 50052
---
apiVersion: v1
kind: Service
metadata:
  name:  category-service-node-port-service
spec:
  type: NodePort
  ports:
    - port: 50052
      targetPort: 50052
      nodePort: 30000
  selector:
    app: category-service-label
