// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/Sokol111/category-service/internal/core/services/categorysrv"
	"github.com/Sokol111/category-service/internal/handlers/cathandler"
	"github.com/Sokol111/category-service/internal/repositories/catrepo"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeServer(port int) *Server {
	categoryRepository := catrepo.NewCategoryRepository()
	categoryService := categorysrv.NewCategoryService(categoryRepository)
	categoryServiceServer := cathandler.NewCategoryServiceServer(categoryService)
	serverServer := NewServer(port, categoryServiceServer)
	return serverServer
}

// wire.go:

var repositories = wire.NewSet(catrepo.NewCategoryRepository)

var services = wire.NewSet(categorysrv.NewCategoryService)

var handlers = wire.NewSet(cathandler.NewCategoryServiceServer)

var server = wire.NewSet(NewServer)
